# logLevel is the log level, if set only message with at least this level is logged
# e.g.: debug -> means error, warning, info and debug messages are logged
# Allowed values: debug | info | warning | error | trace
# Default is info.
logLevel: info

# logDestination defines the log destinations.
#  supported values: stdout | stderr | /path/to/logfile
logDestination: stdout

# webserver configuration
webserver:
  # listenHost is the host address the https server listens for connections.
  # Default is empty, which means all available network interfaces.
  listenHost: 0.0.0.0

  # listenPort is the port the https server listens for connections.
  # Default is 443
  listenPort: 443

  # aiKey is the global api key for the application.
  # Default is empty that means api key authentication is disabled.
  # 12345678
  apiKey: 12345678

  # keyFile is the ssl certificate private key file
  # Default is /opt/manchaster/etc/key.pem
  keyFile: /opt/manchaster/etc/key.pem

  # CertFile is the ssl certificate public key file
  # Default is cert.pem
  # Pfx files are supported as well, in which case KeyFile must be empty and CertFile must point to the pfx file, CertPassword must contain the password to decode the pfx file.
  certFile: /opt/manchaster/etc/cert.pem

  # BlockedIPs is a list of IP addresses or networks that are forbidden from accessing the application.
  # Default is empty, which means no IP addresses or networks are blocked.
  # Multiple IP addresses or networks can be defined separated by a comma
  # e.g.: 192.168.0.1,192.168.0.0/16,10.0.0.0/8,192.168.254.15
  blockedIPs: []
  #    - 192.168.0.1
  #    - 192.168.0.0/16
  #    - 10.0.0.0/8
  #    - 192.168.254.15

  # AllowedIPs is a list of IP addresses that are allowed to access the application.
  # Default is empty, which means all IP addresses are allowed.
  # The value "ALL" allows access from all IP Addresses / IP Networks
  # multiple IP addresses or networks can be defined separated by a comma
  # e.g.: 127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8
  # Note: '::1' is the IPv6 loopback address.
  allowedIPs: []
  #    - ALL
  #    - 127.0.0.1
  #    - ::1
  #    - 192.168.0.0/16
  #    - 10.0.0.0/8

# dataCollectionInterval defines the interval in seconds, in which the gauges are calculated
# default 60 seconds
dataCollectionInterval: 60

# dataFile defines the file in which the counters are saved
# default /opt/s0counter/data/measurement.yaml
dataFile: /opt/s0counter/data/measurement.yaml

# backupInterval defines the interval, in which counters are saved to datafile
# default 60 seconds
backupInterval: 60

mqtt:
  # connection >> defines the connection string to the mqtt broker
  # connection: "tcp://raspberrypi4.fritz.box:1883"
  # retained defines the message retained flag
  retained: false

# meter configurations
# key >> name of device
#    gpio >> S0 input gpio pin
#    bounceTime >> time to wait for a stable signal on gpio pin (ms) to get a "clean" level (suppress key bouncing)
#    unitCounter >> unit of counter eg "kWh, m³, ..."
#    counterConstant >> (Zählerkonstante) >> ticks/unitcounter: e.g. ticks/kWh
#    unitGauge >> unit of gauge (unit/t) eg "kW, l/h, ..."
#    scaleFactor >> scale factor of gauge, based on hour: eg 1000: m³/h >> l/h,  0.27777778 m3/h >> l/s
#    precision >> rounding gauge to a specified number of decimals
#    mqttTopic >> mqtt topic, if it isn't defined, values aren't send to the mqtt broker
meter:
  wallbox:
    gpio: 17
    bounceTime: 1
    unitCounter: "kWh"
    counterConstant: 1000
    unitGauge: "kW"
    scaleFactor: 1
    precision: 0
  #  mqttTopic: test/wallbox/summary
  rawwater:
    gpio: 27
    bounceTime: 1
    unitCounter: "l"
    counterConstant: 1
    unitGauge: "l/h"
    scaleFactor: 1
    precision: 0
  #  mqttTopic: test/rawwater/summary
  portablewater:
    gpio: 22
    bounceTime: 1
    unitCounter: "m³"
    counterConstant: 1000
    unitGauge: "l/s"
    scaleFactor: 0.2777777778
    precision: 0
  #  mqttTopic: test/portablewater/summary

