// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/data": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth\t\"API key must be provided in the header\"": []
                    }
                ],
                "description": "Retrieves the monitoring data for the WATCHIT application, including meter readings.",
                "tags": [
                    "info"
                ],
                "summary": "Get monitoring data",
                "responses": {
                    "200": {
                        "description": "Monitoring data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/s0meters.Data"
                        }
                    },
                    "403": {
                        "description": "Forbidden: Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Retrieves the health data for the application, including memory usage, goroutine count, and version.",
                "tags": [
                    "info"
                ],
                "summary": "Get health data",
                "responses": {
                    "200": {
                        "description": "Health data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/health.Model"
                        }
                    },
                    "403": {
                        "description": "Forbidden: Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/api/monitoring": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth \t\t\"API key must be provided in the header\"": []
                    }
                ],
                "description": "This endpoint returns monitoring data for the WATCHIT system, including health, performance metrics, and system status.",
                "tags": [
                    "info"
                ],
                "summary": "Get monitoring data for WATCHIT",
                "responses": {
                    "200": {
                        "description": "Monitoring data successfully retrieved",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/monitoring.Model"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden: Insufficient permissions",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/api/version": {
            "get": {
                "description": "This endpoint returns the name and version of the application to help with debugging and monitoring.",
                "tags": [
                    "info"
                ],
                "summary": "Get application version and name",
                "responses": {
                    "200": {
                        "description": "Application version and name successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/app.HandleVersion.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.HandleVersion.Response": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "health.Model": {
            "type": "object",
            "properties": {
                "HeapAllocatedBytes": {
                    "description": "HeapAllocatedBytes represents the amount of memory allocated by the heap in bytes.",
                    "type": "integer"
                },
                "HeapAllocatedMB": {
                    "description": "HeapAllocatedMB represents the amount of memory allocated by the heap in megabytes.",
                    "type": "number"
                },
                "HostName": {
                    "description": "HostName is the name of the host machine running the application.",
                    "type": "string"
                },
                "NumGoroutines": {
                    "description": "NumGoroutines is the number of currently running goroutines in the application.",
                    "type": "integer"
                },
                "OperatingSystem": {
                    "description": "OperatingSystem is the name of the operating system on which the application is running.",
                    "type": "string"
                },
                "ProgLang": {
                    "description": "ProgLang represents the version of the Go programming language used.",
                    "type": "string"
                },
                "SysMemoryBytes": {
                    "description": "SysMemoryBytes represents the total system memory in bytes.",
                    "type": "integer"
                },
                "SysMemoryMB": {
                    "description": "SysMemoryMB represents the total system memory in megabytes.",
                    "type": "number"
                },
                "Time": {
                    "description": "Time is the timestamp when the health data was collected, in RFC3339 format.",
                    "type": "string"
                },
                "Version": {
                    "description": "Version indicates the application version.",
                    "type": "string"
                }
            }
        },
        "monitoring.Model": {
            "type": "object",
            "properties": {
                "Description": {
                    "description": "Description provides a human-readable description of the service's status.",
                    "type": "string"
                },
                "Host": {
                    "description": "Host is the host on which the service is running.",
                    "type": "string"
                },
                "Metric": {
                    "description": "Metric indicates the type of metric being reported (e.g., \"gauge\" or \"counter\").\nIf empty, no statistic will be written in Odin.",
                    "type": "string"
                },
                "Service": {
                    "description": "Service is the name of the service being monitored.",
                    "type": "string"
                },
                "State": {
                    "description": "State represents the current state of the service (e.g., \"OK\", \"Error\").\nIf the state is empty, it will be determined based on WATCHIT thresholds.",
                    "type": "string"
                },
                "Value": {
                    "description": "Value holds the actual metric data. The type is ` + "`" + `any` + "`" + ` to accommodate various types of values.\nIf empty, no statistic will be written in Odin."
                }
            }
        },
        "s0meters.Data": {
            "type": "object",
            "properties": {
                "Counter": {
                    "description": "current counter (aktueller Zählerstand), eg kWh, l, m³",
                    "type": "number"
                },
                "Gauge": {
                    "description": "mass flow rate per time unit  (= counter/time(h)), e.g. kW, l/h, m³/h",
                    "type": "number"
                },
                "TimeStamp": {
                    "description": "timestamp of last gauge calculation",
                    "type": "string"
                },
                "UnitCounter": {
                    "description": "unit of current meter counter e.g., kWh, l, m³",
                    "type": "string"
                },
                "UnitGauge": {
                    "description": "unit of gauge, eg Wh, l/s, m³/h",
                    "type": "string"
                }
            }
        },
        "web.ApiError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
