// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves memory usage, goroutine count, version, hostname, Go runtime version, OS, the MQTT connection state, and per meter the raw pulses, the time and age of the last pulse, and the GPIO events lost (counted late, the gauge skips the gap).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get health data",
                "responses": {
                    "200": {
                        "description": "Health data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/health.Model"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/meters": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the current counter and gauge values for all registered S0 meters, keyed by meter name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meters"
                ],
                "summary": "Get all meter readings",
                "responses": {
                    "200": {
                        "description": "Meter readings successfully retrieved",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/s0meters.MeterData"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/meters/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the current counter and gauge values for a specific S0 meter by name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meters"
                ],
                "summary": "Get single meter reading",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meter name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meter reading successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/s0meters.MeterData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Meter not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 while the service delivers readings, 503 while a configured MQTT broker is not connected. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "Application is ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "MQTT broker not connected",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current application name and version. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get application version and name",
                "responses": {
                    "200": {
                        "description": "Application version and name",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "app": {
                                    "type": "string"
                                },
                                "appVersion": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.Model": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "Application name (MODULE)",
                    "type": "string"
                },
                "appVersion": {
                    "description": "Current version of the application",
                    "type": "string"
                },
                "goVersion": {
                    "description": "Go runtime version",
                    "type": "string"
                },
                "heapAllocBytes": {
                    "description": "Allocated heap memory in bytes",
                    "type": "integer"
                },
                "hostname": {
                    "description": "Machine name where the app runs",
                    "type": "string"
                },
                "meters": {
                    "description": "Meters holds the diagnostic state per meter name: raw pulses, the last pulse and the\nGPIO events lost since the last start or reload. Filled in by the caller.",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/s0meters.MeterStatus"
                    }
                },
                "mqtt": {
                    "description": "Mqtt is the state of the broker connection: connected, disconnected (also while\nreconnecting) or disabled when no broker is configured. Filled in by the caller.",
                    "type": "string"
                },
                "numGoroutines": {
                    "description": "Current number of active goroutines",
                    "type": "integer"
                },
                "os": {
                    "description": "Operating system name",
                    "type": "string"
                },
                "sysMemoryBytes": {
                    "description": "Total memory obtained from the OS",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "UTC timestamp when health info was collected (RFC3339)",
                    "type": "string"
                },
                "uptimeSeconds": {
                    "description": "Application uptime in seconds",
                    "type": "number"
                }
            }
        },
        "s0meters.Display": {
            "type": "object",
            "properties": {
                "counter": {
                    "description": "Counter in CounterUnit",
                    "type": "number"
                },
                "counterPrecision": {
                    "description": "Decimal places of Counter",
                    "type": "integer"
                },
                "counterUnit": {
                    "description": "DisplayUnit, or the configured counterUnit",
                    "type": "string"
                },
                "gauge": {
                    "description": "Gauge in GaugeUnit",
                    "type": "number"
                },
                "gaugePrecision": {
                    "description": "Decimal places of Gauge",
                    "type": "integer"
                },
                "gaugeUnit": {
                    "description": "DisplayGaugeUnit, or the configured gaugeUnit",
                    "type": "string"
                }
            }
        },
        "s0meters.MeterData": {
            "type": "object",
            "properties": {
                "counter": {
                    "description": "Total meter value in CounterUnit",
                    "type": "number"
                },
                "counterUnit": {
                    "description": "Counter unit",
                    "type": "string"
                },
                "gauge": {
                    "description": "Flow rate in GaugeUnit",
                    "type": "number"
                },
                "gaugeUnit": {
                    "description": "Gauge unit",
                    "type": "string"
                },
                "meter": {
                    "description": "Meter name from the config, like ecoflowd's \"sn\"",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Time of the reading, local time, whole seconds",
                    "type": "string"
                }
            }
        },
        "s0meters.MeterStatus": {
            "type": "object",
            "properties": {
                "display": {
                    "description": "Counter and gauge in the display units",
                    "allOf": [
                        {
                            "$ref": "#/definitions/s0meters.Display"
                        }
                    ]
                },
                "droppedEvents": {
                    "description": "GPIO events lost since start or reload, see pulsecounter",
                    "type": "integer"
                },
                "gpio": {
                    "description": "GPIO the meter is wired to (BCM numbering)",
                    "type": "integer"
                },
                "lastPulse": {
                    "description": "Time of the last pulse, local time, whole seconds",
                    "type": "string"
                },
                "lastPulseAgeSeconds": {
                    "description": "Seconds since the last pulse, one decimal place",
                    "type": "number"
                },
                "pulses": {
                    "description": "Raw pulse count, including restored pulses",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
